### ISSUE TITLE
Foreseen gnat-r1.eclass problems

### ISSUE THREAD

**Issue by Lucretia** [sarnold/portage-overlay#4]
Reading the new eclass, I've noted the following issues:

```
# Shared/static libraries and binaries SHALL reside in the standard locations
```
Really? Each built lib should be in it's own slot.

```
#  - a Library_Kind attribute equal to ‘dynamic’
```
I have a lib that's designed to be linked statically.

**Comment by sarnold** [comment]
Since gnat.eclass has been superceded by Ada overlay/toolchain let's take this up elsewhere.
